In [1]:
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt
import numpy as np

df1 = pd.read_csv('../Output/general_data_merged.csv')
df2 = pd.read_csv('../Output/employee_hours_stats.csv')
df_merged = pd.merge(df1, df2, on="EmployeeID", how="left")
df_merged.describe()

,Age,DistanceFromHome,Education,EmployeeCount,EmployeeID,JobLevel,MonthlyIncome,NumCompaniesWorked,PercentSalaryHike,StandardHours,...,WorkLifeBalance,JobInvolvement,PerformanceRating,AvgWorkingHours,StdWorkingHours,TotalHours,DaysWorked,OvertimeDays,TotalOvertimeHours,AvgOvertimePerDay
count,4410.000000,4410.000000,4410.000000,4410.0,4410.000000,4410.000000,4410.000000,4410.000000,4410.000000,4410.0,...,4410.000000,4410.000000,4410.000000,4410.000000,4410.000000,4410.000000,4410.000000,4410.000000,4410.000000,4410.000000
mean,36.923810,9.192517,2.912925,1.0,2205.500000,2.063946,65029.312925,2.691837,15.209524,8.0,...,2.763492,2.729932,3.153741,7.700792,0.299578,1821.276283,236.265306,76.153061,47.511444,0.198903
std,9.133301,8.105026,1.023933,0.0,1273.201673,1.106689,47068.888559,2.493912,3.659108,0.0,...,0.703541,0.711400,0.360742,1.340218,0.013721,331.361528,5.503779,100.020061,114.804633,0.480110
min,18.000000,1.000000,1.000000,1.0,1.000000,1.000000,10090.000000,0.000000,11.000000,8.0,...,1.000000,1.000000,3.000000,5.950504,0.254754,1348.803056,225.000000,0.000000,0.000000,0.000000
25%,30.000000,2.000000,2.000000,1.0,1103.250000,1.000000,29110.000000,1.000000,12.000000,8.0,...,2.000000,2.000000,3.000000,6.673333,0.289964,1563.572500,232.000000,0.000000,0.000000,0.000000
50%,36.000000,7.000000,3.000000,1.0,2205.500000,2.000000,49190.000000,2.000000,14.000000,8.0,...,3.000000,3.000000,3.000000,7.406761,0.299544,1745.782222,236.000000,6.000000,0.000000,0.000000
75%,43.000000,14.000000,4.000000,1.0,3307.750000,3.000000,83800.000000,4.000000,18.000000,8.0,...,3.000000,3.000000,3.000000,8.368703,0.308990,1967.295347,241.000000,205.000000,0.300764,0.001269
max,60.000000,29.000000,5.000000,1.0,4410.000000,5.000000,199990.000000,9.000000,25.000000,8.0,...,4.000000,4.000000,4.000000,11.030960,0.344907,2723.378056,248.000000,248.000000,500.378056,2.030960

In [2]:
df_merged.head()

,Age,Attrition,BusinessTravel,Department,DistanceFromHome,Education,EducationField,EmployeeCount,EmployeeID,Gender,...,WorkLifeBalance,JobInvolvement,PerformanceRating,AvgWorkingHours,StdWorkingHours,TotalHours,DaysWorked,OvertimeDays,TotalOvertimeHours,AvgOvertimePerDay
0,51,No,Travel_Rarely,Sales,6,2,Life Sciences,1,1,Female,...,2.0,3,3,7.373651,0.283224,1710.686944,232,0,0.0,0.0
1,31,Yes,Travel_Frequently,Research & Development,10,1,Life Sciences,1,2,Female,...,4.0,2,4,7.718969,0.313351,1821.676667,236,42,0.0,0.0
2,32,No,Travel_Frequently,Research & Development,17,4,Other,1,3,Male,...,1.0,3,3,7.013240,0.311551,1697.204167,242,0,0.0,0.0
3,38,No,Non-Travel,Research & Development,2,5,Life Sciences,1,4,Male,...,3.0,2,3,7.193678,0.284133,1690.514444,235,0,0.0,0.0
4,32,No,Travel_Rarely,Research & Development,10,1,Medical,1,5,Male,...,3.0,3,3,8.006175,0.300656,1961.512778,245,115,0.0,0.0

In [3]:
df_merged.to_csv("../Output/final_df.csv")